language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - phpunit --coverage-clover=coverage.clover
  - if grep -q '5.5' < <(php --version) ; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; else echo "skip coverage upload" ; fi